version: '3.5'
services:

  web:
    container_name: WEBServer
    build: ./services/web
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    volumes:
      - ./services/web/app/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - variables.env
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=5000
      - APP_FOLDER=/usr/src/app
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgresDB
    build:
      context: ./services/db/
      dockerfile: Dockerfile
    env_file:
      - variables.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5445:5432"

volumes:
  postgres_data: